<?php

namespace Database\Seeders;

use App\Http\Requests\Freepik\AiImageClassifierRequest;
use App\Http\Requests\Freepik\ClassicFastGenerateRequest;
use App\Http\Requests\Freepik\DownloadResourceFormatRequest;
use App\Http\Requests\Freepik\FluxDevGenerateRequest;
use App\Http\Requests\Freepik\IconGenerationRequest;
use App\Http\Requests\Freepik\ImageExpandFluxProRequest;
use App\Http\Requests\Freepik\Imagen3GenerateRequest;
use App\Http\Requests\Freepik\KlingElementsVideoRequest;
use App\Http\Requests\Freepik\KlingElementsVideoStatusRequest;
use App\Http\Requests\Freepik\KlingImageToVideoRequest;
use App\Http\Requests\Freepik\KlingImageToVideoStatusRequest;
use App\Http\Requests\Freepik\KlingTextToVideoRequest;
use App\Http\Requests\Freepik\LoraCharacterTrainRequest;
use App\Http\Requests\Freepik\LoraStyleTrainRequest;
use App\Http\Requests\Freepik\MysticGenerateRequest;
use App\Http\Requests\Freepik\ReimagineFluxRequest;
use App\Http\Requests\Freepik\RelightImageRequest;
use App\Http\Requests\Freepik\RemoveBackgroundRequest;
use App\Http\Requests\Freepik\StockContentRequest;
use App\Http\Requests\Freepik\StyleTransferRequest;
use App\Http\Requests\Freepik\UpscaleImageRequest;
use Illuminate\Database\Seeder;

class FreepikServiceProviderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $serviceTypes = [
            [
                'name' => 'Stock Content',
                'description' => 'Get stock resources from Freepik with full filtering support',
                'parameter' => [
                    'page' => [
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'The page number for pagination.',
                        'example' => 1,
                        'validation' => 'nullable|integer',
                    ],
                    'limit' => [
                        'type' => 'integer',
                        'required' => true,
                        'description' => 'The number of items to return per page.',
                        'example' => 20,
                        'validation' => 'required|integer|min:1|max:100',
                    ],
                    'order' => [
                        'type' => 'string',
                        'required' => true,
                        'enum' => ['relevance', 'recent'],
                        'description' => 'The sorting order for the results.',
                        'example' => 'relevance',
                        'validation' => 'required|string|in:relevance,recent',
                    ],
                    'term' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'The search term.',
                        'example' => null,
                        'validation' => 'nullable|string',
                    ],
                    'slug' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'The resource slug.',
                        'example' => null,
                        'validation' => 'nullable|string',
                    ],
                    'filters[orientation][landscape]' => [
                        'type' => 'integer',
                        'required' => false,
                        'enum' => [0, 1],
                        'description' => 'Filter by landscape orientation.',
                        'example' => null,
                        'validation' => 'nullable|integer|in:0,1',
                    ],
                    'filters[orientation][portrait]' => [
                        'type' => 'integer',
                        'required' => false,
                        'enum' => [0, 1],
                        'description' => 'Filter by portrait orientation.',
                        'example' => null,
                        'validation' => 'nullable|integer|in:0,1',
                    ],
                    'filters[orientation][square]' => [
                        'type' => 'integer',
                        'required' => false,
                        'enum' => [0, 1],
                        'description' => 'Filter by square orientation.',
                        'example' => null,
                        'validation' => 'nullable|integer|in:0,1',
                    ],
                    'filters[orientation][panoramic]' => [
                        'type' => 'integer',
                        'required' => false,
                        'enum' => [0, 1],
                        'description' => 'Filter by panoramic orientation.',
                        'example' => null,
                        'validation' => 'nullable|integer|in:0,1',
                    ],
                    'filters[content_type][photo]' => [
                        'type' => 'integer',
                        'required' => false,
                        'enum' => [0, 1],
                        'description' => 'Filter by content type: photo.',
                        'example' => null,
                        'validation' => 'nullable|integer|in:0,1',
                    ],
                    'filters[content_type][psd]' => [
                        'type' => 'integer',
                        'required' => false,
                        'enum' => [0, 1],
                        'description' => 'Filter by content type: psd.',
                        'example' => null,
                        'validation' => 'nullable|integer|in:0,1',
                    ],
                    'filters[content_type][vector]' => [
                        'type' => 'integer',
                        'required' => false,
                        'enum' => [0, 1],
                        'description' => 'Filter by content type: vector.',
                        'example' => null,
                        'validation' => 'nullable|integer|in:0,1',
                    ],
                    'filters[license][freemium]' => [
                        'type' => 'integer',
                        'required' => false,
                        'enum' => [0, 1],
                        'description' => 'Filter by freemium license.',
                        'example' => null,
                        'validation' => 'nullable|integer|in:0,1',
                    ],
                    'filters[license][premium]' => [
                        'type' => 'integer',
                        'required' => false,
                        'enum' => [0, 1],
                        'description' => 'Filter by premium license.',
                        'example' => null,
                        'validation' => 'nullable|integer|in:0,1',
                    ],
                    'filters[people][include]' => [
                        'type' => 'integer',
                        'required' => false,
                        'enum' => [0, 1],
                        'description' => 'Filter to include people.',
                        'example' => null,
                        'validation' => 'nullable|integer|in:0,1',
                    ],
                    'filters[people][exclude]' => [
                        'type' => 'integer',
                        'required' => false,
                        'enum' => [0, 1],
                        'description' => 'Filter to exclude people.',
                        'example' => null,
                        'validation' => 'nullable|integer|in:0,1',
                    ],
                    'filters[people][number]' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['1', '2', '3', 'more_than_three'],
                        'description' => 'Filter by the number of people.',
                        'example' => null,
                        'validation' => 'nullable|string|in:1,2,3,more_than_three',
                    ],
                    'filters[people][age]' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['infant', 'child', 'teen', 'young-adult', 'adult', 'senior', 'elder'],
                        'description' => 'Filter by age group.',
                        'example' => null,
                        'validation' => 'nullable|string|in:infant,child,teen,young-adult,adult,senior,elder',
                    ],
                    'filters[people][gender]' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['male', 'female'],
                        'description' => 'Filter by gender.',
                        'example' => null,
                        'validation' => 'nullable|string|in:male,female',
                    ],
                    'filters[people][ethnicity]' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['south-asian', 'middle-eastern', 'east-asian', 'black', 'hispanic', 'indian', 'white', 'multiracial', 'southeast-asian'],
                        'description' => 'Filter by ethnicity.',
                        'example' => null,
                        'validation' => 'nullable|string|in:south-asian,middle-eastern,east-asian,black,hispanic,indian,white,multiracial,southeast-asian',
                    ],
                    'filters[period]' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['last-month', 'last-quarter', 'last-semester', 'last-year'],
                        'description' => 'Filter by time period.',
                        'example' => null,
                        'validation' => 'nullable|string|in:last-month,last-quarter,last-semester,last-year',
                    ],
                    'filters[color]' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['black', 'blue', 'gray', 'green', 'orange', 'red', 'white', 'yellow', 'purple', 'cyan', 'pink'],
                        'description' => 'Filter by color.',
                        'example' => null,
                        'validation' => 'nullable|string|in:black,blue,gray,green,orange,red,white,yellow,purple,cyan,pink',
                    ],
                    'filters[author]' => [
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'Filter by author ID.',
                        'example' => null,
                        'validation' => 'nullable|integer',
                    ],
                    'filters[ai-generated][excluded]' => [
                        'type' => 'integer',
                        'required' => false,
                        'enum' => [0, 1],
                        'description' => 'Exclude AI-generated content.',
                        'example' => null,
                        'validation' => 'nullable|integer|in:0,1',
                    ],
                    'filters[ai-generated][only]' => [
                        'type' => 'integer',
                        'required' => false,
                        'enum' => [0, 1],
                        'description' => 'Include only AI-generated content.',
                        'example' => null,
                        'validation' => 'nullable|integer|in:0,1',
                    ],
                    'filters[vector][type]' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['jpg', 'ai', 'eps', 'svg'],
                        'description' => 'Filter vectors by type.',
                        'example' => null,
                        'validation' => 'nullable|string|in:jpg,ai,eps,svg',
                    ],
                    'filters[vector][style]' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['watercolor', 'flat', 'cartoon', 'geometric', 'gradient', 'isometric', '3d', 'hand-drawn'],
                        'description' => 'Filter vectors by style.',
                        'example' => null,
                        'validation' => 'nullable|string|in:watercolor,flat,cartoon,geometric,gradient,isometric,3d,hand-drawn',
                    ],
                    'filters[psd][type]' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['jpg', 'psd'],
                        'description' => 'Filter PSDs by type.',
                        'example' => null,
                        'validation' => 'nullable|string|in:jpg,psd',
                    ],
                    'filters[ids]' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Filter by a list of resource IDs.',
                        'example' => null,
                        'validation' => 'nullable|string',
                    ],
                ],
                'path_parameters' => [],
                'example' => [
                    'page' => 1,
                    'limit' => 20,
                    'order' => 'relevance',
                ],
                'request_class_name' => StockContentRequest::class,
                'function_name' => 'stockContent',
            ],
            [
                'name' => 'Resource Detail',
                'description' => 'Get detailed info about a specific Freepik resource',
                'parameter' => [],
                'path_parameters' => [
                    'resource_id' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'The ID of the resource to retrieve details for.',
                        'example' => '7663349',
                        'validation' => 'required|string',
                    ],
                ],
                'request_class_name' => null,
                'function_name' => 'resourceDetail',
            ],
            [
                'name' => 'Download resource',
                'description' => 'Get download link for a Freepik resource',
                'parameter' => [],
                'path_parameters' => [
                    'resource_id' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'The ID of the resource to download.',
                        'example' => '7663349',
                        'validation' => 'required|string',
                    ],
                ],
                'request_class_name' => null,
                'function_name' => 'downloadResource',
            ],
            [
                'name' => 'Download Resource Format',
                'description' => 'Download a Freepik resource in the specified format',
                'parameter' => [
                    'resource_id' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'The ID of the resource to download.',
                        'example' => '150898146',
                        'validation' => 'required|string',
                    ],
                    'format' => [
                        'type' => 'string',
                        'required' => true,
                        'enum' => ['psd', 'ai', 'eps', 'atn', 'fonts', 'resources', 'png', 'jpg', '3d-render', 'svg', 'mockup'],
                        'description' => 'The desired format for the download.',
                        'example' => 'psd',
                        'validation' => 'required|string|in:psd,ai,eps,atn,fonts,resources,png,jpg,3d-render,svg,mockup',
                    ],
                ],
                'path_parameters' => [],
                'example' => [
                    'resource_id' => 150898146,
                    'format' => 'psd',
                ],
                'request_class_name' => DownloadResourceFormatRequest::class,
                'function_name' => 'downloadResourceFormat',
            ],
            [
                'name' => 'AI Image Classifier',
                'description' => 'Classify an image via URL to determine if it was AI-generated.',
                'parameter' => [
                    'image_url' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'The URL of the image to classify.',
                        'example' => 'https://publiish.io/ipfs/QmTkm5aAqNPgc3rXKTjYJ1VVB86xWJGofZX5wiRXHeew7f',
                        'validation' => 'required|string|url',
                    ],
                ],
                'path_parameters' => [],
                'example' => [
                    'image_url' => 'https://publiish.io/ipfs/QmTkm5aAqNPgc3rXKTjYJ1VVB86xWJGofZX5wiRXHeew7f',
                ],
                'request_class_name' => AiImageClassifierRequest::class,
                'function_name' => 'aiImageClassifier',
            ],
            [
                'name' => 'Icon Generation',
                'description' => 'Submit a text prompt to generate AI icon previews. Result is sent via webhook.',
                'parameter' => [
                    'prompt' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Text prompt describing the icon you want to generate',
                        'example' => 'Cute robot with camera in flat vector style',
                        'validation' => 'required|string',
                    ],
                ],
                'path_parameters' => [],
                'example' => [
                    'prompt' => 'Cute robot with camera in flat vector style',
                ],
                'request_class_name' => IconGenerationRequest::class,
                'function_name' => 'iconGeneration',
            ],
            [
                'name' => 'Get result of Icon Generation by task_id',
                'description' => 'Retrieve the result of a previously submitted icon generation task using task_id.',
                'parameter' => [],
                'path_parameters' => [
                    'task_id' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'The task_id received from the iconGeneration endpoint.',
                        'example' => '796dd3c1-c50b-42bc-a9e2-a892eef53438',
                        'validation' => 'required|string',
                    ],
                ],
                'request_class_name' => null,
                'function_name' => 'getIconGenerationResult',
            ],
            [
                'name' => 'Video Generation Image to Video',
                'description' => 'Generate a video from an image prompt using Freepik’s Kling v2.1 Master model. Supports Image to Video modes with detailed input parameters.',
                'parameter' => [
                    'model' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['kling-v2-1-master', 'kling-v2-1-pro', 'kling-v2-1-std', 'kling-v2', 'kling-pro', 'kling-std'],
                        'description' => 'Model of the generated video. Available options: kling-v2-1-master, kling-v2-1-pro, kling-v2-1-std, kling-v2, kling-pro, kling-std.',
                        'example' => 'kling-v2-1-master',
                        'validation' => 'nullable|string|in:kling-v2-1-master,kling-v2-1-pro,kling-v2-1-std,kling-v2,kling-pro,kling-std',
                    ],
                    'duration' => [
                        'type' => 'string',
                        'required' => true,
                        'enum' => ['5', '10'],
                        'description' => 'Duration of the generated video in seconds. Available options: 5, 10.',
                        'example' => '10',
                        'validation' => 'required|string|in:5,10',
                    ],
                    'image' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Reference image. Supports URL. Max 10MB, min 300x300px, aspect ratio 1:2.5 to 2.5:1.',
                        'example' => 'https://publiish.io/ipfs/QmePMNQ1BYCsaJwCpA4sbGpYxgiEznzJwPDMHir9FdUiYN',
                        'validation' => 'nullable|string',
                    ],
                    'image_tail' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Reference Image - End frame control. Supports URL. For URL, must be publicly accessible. Must follow the same format requirements as the \'image\' field. (Optional) Not compatible with standard mode.',
                        'example' => 'https://publiish.io/ipfs/QmePMNQ1BYCsaJwCpA4sbGpYxgiEznzJwPDMHir9FdUiYN',
                        'validation' => 'nullable|string',
                    ],
                    'prompt' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Text prompt describing the desired motion. Required if image is not provided.',
                        'example' => 'Cinematic view of a mountain range fading into mist, soft lighting, epic atmosphere',
                        'validation' => 'nullable|string',
                    ],
                    'negative_prompt' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Describe what to avoid in the generated video.',
                        'example' => 'blurry, low-quality, distorted, overexposed',
                        'validation' => 'nullable|string',
                    ],
                    'cfg_scale' => [
                        'type' => 'number',
                        'required' => false,
                        'description' => 'Higher = stronger relevance to prompt (0-1). Default is 0.5.',
                        'example' => 0.3,
                        'validation' => 'nullable|numeric|min:0|max:1',
                    ],
                    'static_mask' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Static mask image URL. Must match resolution and aspect ratio of input image.',
                        'example' => 'https://publiish.io/ipfs/Qme7SZ1t9PbGKAesTA24EDu7pEs3J1JkWDt9qwQdaocYRB',
                        'validation' => 'nullable|string',
                    ],
                    'dynamic_masks' => [
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Array of dynamic masks with motion trajectories.',
                        'example' => [],
                        'validation' => 'nullable|array',
                        'items' => [
                            'type' => 'object',
                            'required' => ['mask', 'trajectories'],
                            'properties' => [
                                'mask' => [
                                    'type' => 'string',
                                    'required' => true,
                                    'description' => 'Dynamic mask image URL',
                                    'example' => 'https://publiish.io/ipfs/QmRPNoFMcYFmzJuZgd4t3BDyfELAGCwNtGSb5i5AbXkcpf',
                                    'validation' => 'required|string',
                                ],
                                'trajectories' => [
                                    'type' => 'array',
                                    'required' => true,
                                    'description' => 'Array of trajectory coordinates.',
                                    'example' => [],
                                    'validation' => 'required|array',
                                    'items' => [
                                        'type' => 'object',
                                        'required' => ['x', 'y'],
                                        'properties' => [
                                            'x' => [
                                                'type' => 'integer',
                                                'required' => true,
                                                'description' => 'X-coordinate of the trajectory point.',
                                                'example' => 120,
                                                'validation' => 'required|integer',
                                            ],
                                            'y' => [
                                                'type' => 'integer',
                                                'required' => true,
                                                'description' => 'Y-coordinate of the trajectory point.',
                                                'example' => 200,
                                                'validation' => 'required|integer',
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
                'path_parameters' => [],
                'example' => [
                    'model' => 'kling-v2-1-master',
                    'duration' => '10',
                    'image' => 'https://publiish.io/ipfs/QmePMNQ1BYCsaJwCpA4sbGpYxgiEznzJwPDMHir9FdUiYN',
                    'image_tail' => 'https://publiish.io/ipfs/QmePMNQ1BYCsaJwCpA4sbGpYxgiEznzJwPDMHir9FdUiYN',
                    'prompt' => 'Cinematic view of a mountain range fading into mist, soft lighting, epic atmosphere',
                    'negative_prompt' => 'blurry, low-quality, distorted, overexposed',
                    'cfg_scale' => 0.3,
                    'static_mask' => 'https://publiish.io/ipfs/Qme7SZ1t9PbGKAesTA24EDu7pEs3J1JkWDt9qwQdaocYRB',
                    'dynamic_masks' => [
                        [
                            'mask' => 'https://publiish.io/ipfs/QmRPNoFMcYFmzJuZgd4t3BDyfELAGCwNtGSb5i5AbXkcpf',
                            'trajectories' => [
                                [
                                    'x' => 120,
                                    'y' => 200,
                                ],
                            ],
                        ],
                    ],
                ],
                'request_class_name' => KlingImageToVideoRequest::class,
                'function_name' => 'klingVideoGenerationImageToVideo',
            ],
            [
                'name' => 'Get status of Video Generation Image to Video task',
                'description' => 'Check the current status of a Kling v2.1 Master image-to-video generation task by task ID.',
                'parameter' => [
                    'model' => [
                        'type' => 'string',
                        'required' => true,
                        'enum' => ['kling-v2-1-master', 'kling-v2-1-pro', 'kling-v2-1-std', 'kling-v2', 'kling-pro', 'kling-std'],
                        'description' => 'Model of the generated video in seconds. Available options: kling-v2-1-master,kling-v2-1-pro,kling-v2-1-std,kling-v2,kling-pro,kling-std.',
                        'example' => 'kling-v2-1-master',
                        'validation' => 'required|string|in:kling-v2-1-master,kling-v2-1-pro,kling-v2-1-std,kling-v2,kling-pro,kling-std',
                    ],
                ],
                'path_parameters' => [
                    'task_id' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'ID of the video generation task',
                        'example' => '046b6c7f-0b8a-43b9-b35d-6489e6daee91',
                        'validation' => 'required|string',
                    ],
                ],
                'example' => [
                    'model' => 'kling-v2-1-master',
                ],
                'request_class_name' => KlingImageToVideoStatusRequest::class,
                'function_name' => 'klingVideoGenerationImageToVideoStatus',
            ],
            [
                'name' => 'Video Generation Text to Video',
                'description' => 'Generate a video from an text prompt using Freepik’s Kling v2.1 Master model. Supports Text to Video modes with detailed input parameters.',
                'parameter' => [
                    'duration' => [
                        'type' => 'string',
                        'required' => true,
                        'enum' => ['5', '10'],
                        'description' => 'Duration of the generated video in seconds. Available options: 5, 10.',
                        'example' => '5',
                        'validation' => 'required|string|in:5,10',
                    ],
                    'prompt' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Text prompt describing the desired motion. Max 2500 characters.',
                        'example' => 'A sunset over the ocean with crashing waves',
                        'validation' => 'nullable|string',
                    ],
                    'negative_prompt' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Describe what to avoid in the generated video.',
                        'example' => 'low resolution, night scene',
                        'validation' => 'nullable|string',
                    ],
                    'aspect_ratio' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['widescreen_16_9', 'social_story_9_16', 'square_1_1'],
                        'description' => 'Aspect ratio for generated video (only used when image is not provided).',
                        'example' => 'widescreen_16_9',
                        'validation' => 'nullable|string|in:widescreen_16_9,social_story_9_16,square_1_1',
                    ],
                    'cfg_scale' => [
                        'type' => 'number',
                        'required' => false,
                        'description' => 'Higher = stronger relevance to prompt (0-1). Default is 0.5.',
                        'example' => 0.5,
                        'validation' => 'nullable|numeric|min:0|max:1',
                    ],
                ],
                'path_parameters' => [],
                'example' => [
                    'duration' => 5,
                    'prompt' => 'A sunset over the ocean with crashing waves',
                    'negative_prompt' => 'low resolution, night scene',
                    'aspect_ratio' => 'widescreen_16_9',
                    'cfg_scale' => 0.5,
                ],
                'request_class_name' => KlingTextToVideoRequest::class,
                'function_name' => 'klingVideoGenerationTextToVideo',
            ],
            [
                'name' => 'Get status of Video Generation Text to Video task',
                'description' => 'Check the current status of a Kling v2.1 Master text-to-video generation task by task ID.',
                'parameter' => [],
                'path_parameters' => [
                    'task_id' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'ID of the video generation task',
                        'example' => '046b6c7f-0b8a-43b9-b35d-6489e6daee91',
                        'validation' => 'required|string',
                    ],
                ],
                'request_class_name' => null,
                'function_name' => 'klingVideoGenerationTextToVideoStatus',
            ],
            [
                'name' => 'Video Generation Elements',
                'description' => 'Create a video from 1–4 images with optional prompts, duration, aspect ratio, and webhook.',
                'parameter' => [
                    'images[]' => [
                        'type' => 'array',
                        'required' => true,
                        'description' => 'Array of up to 4 image URLs (publicly accessible)',
                        'example' => ['https://publiish.io/ipfs/QmePMNQ1BYCsaJwCpA4sbGpYxgiEznzJwPDMHir9FdUiYN', 'https://publiish.io/ipfs/QmRPNoFMcYFmzJuZgd4t3BDyfELAGCwNtGSb5i5AbXkcpf'],
                        'validation' => 'required|array|max:4',
                    ],
                    'prompt' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'The text prompt for the video.',
                        'example' => null,
                        'validation' => 'nullable|string|max:2500',
                    ],
                    'negative_prompt' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'The negative prompt for the video.',
                        'example' => null,
                        'validation' => 'nullable|string|max:2500',
                    ],
                    'duration' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['5', '10'],
                        'description' => 'The duration of the video in seconds.',
                        'example' => '5',
                        'validation' => 'nullable|string|in:5,10',
                    ],
                    'aspect_ratio' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['widescreen_16_9', 'social_story_9_16', 'square_1_1'],
                        'description' => 'The aspect ratio of the video.',
                        'example' => null,
                        'validation' => 'nullable|string|in:widescreen_16_9,social_story_9_16,square_1_1',
                    ],
                ],
                'path_parameters' => [],
                'example' => [
                    'images' => [
                        'https://publiish.io/ipfs/QmePMNQ1BYCsaJwCpA4sbGpYxgiEznzJwPDMHir9FdUiYN',
                        'https://publiish.io/ipfs/QmRPNoFMcYFmzJuZgd4t3BDyfELAGCwNtGSb5i5AbXkcpf',
                    ],
                    'duration' => 5,
                    'prompt' => 'A sunset over the ocean with crashing waves',
                    'negative_prompt' => 'low resolution, night scene',
                    'aspect_ratio' => 'widescreen_16_9',
                ],
                'request_class_name' => KlingElementsVideoRequest::class,
                'function_name' => 'klingElementsVideo',
            ],
            [
                'name' => 'Get status of Video Generation Elements task',
                'description' => 'Check the current status of a Kling v2.1 Master image-to-video generation task by task ID.',
                'parameter' => [
                    'model' => [
                        'type' => 'string',
                        'required' => true,
                        'enum' => ['kling-elements-pro', 'kling-elements-std'],
                        'description' => 'Model of the generated video in seconds. Available options: kling-elements-pro,kling-elements-std.',
                        'example' => 'kling-elements-pro',
                        'validation' => 'required|string|in:kling-elements-pro,kling-elements-std',
                    ],
                ],
                'path_parameters' => [
                    'task_id' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'ID of the video generation task',
                        'example' => '046b6c7f-0b8a-43b9-b35d-6489e6daee91',
                        'validation' => 'required|string',
                    ],
                ],
                'example' => [
                    'model' => 'kling-elements-pro',
                ],
                'request_class_name' => KlingElementsVideoStatusRequest::class,
                'function_name' => 'klingElementsVideoStatus',
            ],
            [
                'name' => 'Mystic LoRAs List',
                'description' => 'Get list of LoRAs (custom styles and defaults) for Mystic AI',
                'parameter' => [],
                'path_parameters' => [],
                'request_class_name' => null,
                'function_name' => 'getLoras',
            ],
            [
                'name' => 'Mystic Image Generation',
                'description' => 'Create ultra-realistic AI images using Mystic from Freepik',
                'parameter' => [
                    'prompt' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'AI Model Prompt Description. The text that describes the image you want to generate.',
                        'example' => 'A futuristic cityscape at sunset, flying cars, glowing neon lights, cyberpunk vibe',
                        'validation' => 'required|string',
                    ],
                    'structure_reference' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Base64 image to use as structure reference to influence the shape.',
                        'example' => 'https://publiish.io/ipfs/QmPE5opZZhpeHypZzG3qJE5cbCNZ28SibBa9xo4MqsgF9H',
                        'validation' => 'nullable|string',
                    ],
                    'structure_strength' => [
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'Strength to maintain the structure of the original image.',
                        'example' => 60,
                        'validation' => 'nullable|integer|min:0|max:100',
                    ],
                    'style_reference' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Base64 image to use as style reference to influence aesthetics.',
                        'example' => 'https://publiish.io/ipfs/QmTjCdTXQ2M1JPQHMuciYGQ2BWLVXum73PEJ8KY1znV4TV',
                        'validation' => 'nullable|string',
                    ],
                    'adherence' => [
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'Higher values make the generation more faithful to the prompt.',
                        'example' => 70,
                        'validation' => 'nullable|integer|min:0|max:100',
                    ],
                    'hdr' => [
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'Controls image detail and "AI look" tradeoff.',
                        'example' => 80,
                        'validation' => 'nullable|integer|min:0|max:100',
                    ],
                    'resolution' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['1k', '2k', '4k'],
                        'description' => 'Resolution of the generated image.',
                        'example' => '2k',
                        'validation' => 'nullable|string|in:1k,2k,4k',
                    ],
                    'aspect_ratio' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['square_1_1', 'classic_4_3', 'traditional_3_4', 'widescreen_16_9', 'social_story_9_16', 'smartphone_horizontal_20_9', 'smartphone_vertical_9_20', 'standard_3_2', 'portrait_2_3', 'horizontal_2_1', 'vertical_1_2', 'social_5_4', 'social_post_4_5'],
                        'description' => 'Aspect ratio of the generated image.',
                        'example' => 'square_1_1',
                        'validation' => 'nullable|string|in:square_1_1,classic_4_3,traditional_3_4,widescreen_16_9,social_story_9_16,smartphone_horizontal_20_9,smartphone_vertical_9_20,standard_3_2,portrait_2_3,horizontal_2_1,vertical_1_2,social_5_4,social_post_4_5',
                    ],
                    'model' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['realism', 'fluid', 'zen'],
                        'description' => 'Model to use for generation.',
                        'example' => 'realism',
                        'validation' => 'nullable|string|in:realism,fluid,zen',
                    ],
                    'creative_detailing' => [
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'Controls detail per pixel with tradeoff on HDR/artificial look.',
                        'example' => 45,
                        'validation' => 'nullable|integer|min:0|max:100',
                    ],
                    'engine' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['automatic', 'magnific_illusio', 'magnific_sharpy', 'magnific_sparkle'],
                        'description' => 'Engine choice for the AI model.',
                        'example' => 'automatic',
                        'validation' => 'nullable|string|in:automatic,magnific_illusio,magnific_sharpy,magnific_sparkle',
                    ],
                    'fixed_generation' => [
                        'type' => 'boolean',
                        'required' => false,
                        'description' => 'If true, same input produces the same image (fixed randomness).',
                        'example' => false,
                        'validation' => 'nullable|boolean',
                    ],
                    'filter_nsfw' => [
                        'type' => 'boolean',
                        'required' => false,
                        'description' => 'When enabled, NSFW images are replaced with a black image.',
                        'example' => true,
                        'validation' => 'nullable|boolean',
                    ],
                    'styling' => [
                        'type' => 'object',
                        'required' => false,
                        'description' => 'Styling options for the image',
                        'example' => null,
                        'validation' => 'nullable|array',
                    ],
                ],
                'path_parameters' => [],
                'example' => [
                    'prompt' => 'A futuristic cityscape at sunset, flying cars, glowing neon lights, cyberpunk vibe',
                    'structure_reference' => 'https://publiish.io/ipfs/QmPE5opZZhpeHypZzG3qJE5cbCNZ28SibBa9xo4MqsgF9H',
                    'structure_strength' => 60,
                    'style_reference' => 'https://publiish.io/ipfs/QmTjCdTXQ2M1JPQHMuciYGQ2BWLVXum73PEJ8KY1znV4TV',
                    'adherence' => 70,
                    'hdr' => 80,
                    'resolution' => '2k',
                    'aspect_ratio' => 'square_1_1',
                    'model' => 'realism',
                    'creative_detailing' => 45,
                    'engine' => 'automatic',
                    'fixed_generation' => false,
                    'filter_nsfw' => true,
                    'styling' => [
                        'styles' => [
                            [
                                'name' => 'cyberpunk',
                                'strength' => 100,
                            ],
                        ],
                        'characters' => [
                            [
                                'id' => '110',
                                'strength' => 100,
                            ],
                        ],
                        'colors' => [
                            [
                                'color' => '#00FFFF',
                                'weight' => 0.6,
                            ],
                            [
                                'color' => '#FF69B4',
                                'weight' => 0.4,
                            ],
                        ],
                    ],
                ],
                'request_class_name' => MysticGenerateRequest::class,
                'function_name' => 'generateMysticImage',
            ],
            [
                'name' => 'Mystic Image Generation Task Status',
                'description' => 'Get the status of the Mystic task',
                'parameter' => [],
                'path_parameters' => [
                    'task_id' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'ID of the Mystic generation task',
                        'example' => '046b6c7f-0b8a-43b9-b35d-6489e6daee91',
                        'validation' => 'required|string',
                    ],
                ],
                'request_class_name' => null,
                'function_name' => 'getMysticTaskStatus',
            ],
            [
                'name' => 'LoRAs Custom Style Training',
                'description' => 'Create your own custom LoRA style by training with images',
                'parameter' => [
                    'name' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Name of the LoRA style used to identify the style in the system.',
                        'example' => 'neon-cyberpunk-style',
                        'validation' => 'required|string',
                    ],
                    'quality' => [
                        'type' => 'string',
                        'required' => true,
                        'enum' => ['medium', 'high', 'ultra'],
                        'description' => 'Quality of the LoRA style.',
                        'example' => 'high',
                        'validation' => 'required|string|in:medium,high,ultra',
                    ],
                    'images' => [
                        'type' => 'array',
                        'required' => true,
                        'description' => 'List of image URLs to train the LoRA style.',
                        'example' => ['https://publiish.io/ipfs/QmRBe3ZDEBDH18JEgDuFdTShzw3Xy1s94bY6dtcBAnH4tu', 'https://publiish.io/ipfs/QmRPNoFMcYFmzJuZgd4t3BDyfELAGCwNtGSb5i5AbXkcpf', 'https://publiish.io/ipfs/QmePMNQ1BYCsaJwCpA4sbGpYxgiEznzJwPDMHir9FdUiYN', 'https://publiish.io/ipfs/QmPnAKihJS1shKqnA4UqQ6bvkw29j8yFW4MJTb6KZA1e6Q', 'https://publiish.io/ipfs/QmdHRXQ8sX2d648gnCa2CXUjeJmreS8654vqwd9JS6m8GN', 'https://publiish.io/ipfs/QmPE5opZZhpeHypZzG3qJE5cbCNZ28SibBa9xo4MqsgF9H'],
                        'validation' => 'required|array|min:6|max:20',
                    ],
                    'description' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Description of the LoRA style.',
                        'example' => 'A high-quality cyberpunk visual style with neon lights, futuristic elements, and strong contrast. Inspired by sci-fi films and urban night scenes.',
                        'validation' => 'nullable|string',
                    ],
                ],
                'path_parameters' => [],
                'example' => [
                    'name' => 'neon-cyberpunk-style',
                    'quality' => 'high',
                    'images' => [
                        'https://publiish.io/ipfs/QmRBe3ZDEBDH18JEgDuFdTShzw3Xy1s94bY6dtcBAnH4tu',
                        'https://publiish.io/ipfs/QmRPNoFMcYFmzJuZgd4t3BDyfELAGCwNtGSb5i5AbXkcpf',
                        'https://publiish.io/ipfs/QmePMNQ1BYCsaJwCpA4sbGpYxgiEznzJwPDMHir9FdUiYN',
                        'https://publiish.io/ipfs/QmPnAKihJS1shKqnA4UqQ6bvkw29j8yFW4MJTb6KZA1e6Q',
                        'https://publiish.io/ipfs/QmdHRXQ8sX2d648gnCa2CXUjeJmreS8654vqwd9JS6m8GN',
                        'https://publiish.io/ipfs/QmPE5opZZhpeHypZzG3qJE5cbCNZ28SibBa9xo4MqsgF9H',
                    ],
                    'description' => 'A high-quality cyberpunk visual style with neon lights, futuristic elements, and strong contrast. Inspired by sci-fi films and urban night scenes.',
                ],
                'request_class_name' => LoraStyleTrainRequest::class,
                'function_name' => 'createLoraStyle',
            ],
            [
                'name' => 'LoRAs Custom Character Training',
                'description' => 'No description provided.',
                'parameter' => [
                    'name' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'The name of the character.',
                        'example' => 'cyber_hero_neo',
                        'validation' => 'required|string',
                    ],
                    'quality' => [
                        'type' => 'string',
                        'required' => true,
                        'enum' => ['medium', 'high', 'ultra'],
                        'description' => 'Quality of the LoRA character',
                        'example' => 'high',
                        'validation' => 'required|string|in:medium,high,ultra',
                    ],
                    'gender' => [
                        'type' => 'string',
                        'required' => true,
                        'enum' => ['male', 'female', 'neutral', 'custom'],
                        'description' => 'Gender of the character',
                        'example' => 'male',
                        'validation' => 'required|string|in:male,female,neutral,custom',
                    ],
                    'images' => [
                        'type' => 'array',
                        'required' => true,
                        'description' => 'An array of image URLs for training.',
                        'example' => ['https://publiish.io/ipfs/QmRBe3ZDEBDH18JEgDuFdTShzw3Xy1s94bY6dtcBAnH4tu', 'https://publiish.io/ipfs/QmRPNoFMcYFmzJuZgd4t3BDyfELAGCwNtGSb5i5AbXkcpf', 'https://publiish.io/ipfs/QmePMNQ1BYCsaJwCpA4sbGpYxgiEznzJwPDMHir9FdUiYN', 'https://publiish.io/ipfs/QmPnAKihJS1shKqnA4UqQ6bvkw29j8yFW4MJTb6KZA1e6Q', 'https://publiish.io/ipfs/QmdHRXQ8sX2d648gnCa2CXUjeJmreS8654vqwd9JS6m8GN', 'https://publiish.io/ipfs/QmPE5opZZhpeHypZzG3qJE5cbCNZ28SibBa9xo4MqsgF9H', 'https://publiish.io/ipfs/QmRTn93jATdpcpCg1nRfAExc8shh9Hmhbd8PHnXBrLJYAa', 'https://publiish.io/ipfs/QmTjCdTXQ2M1JPQHMuciYGQ2BWLVXum73PEJ8KY1znV4TV'],
                        'validation' => 'required|array|min:8|max:20',
                    ],
                    'description' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'A description for the character.',
                        'example' => 'A futuristic male character with a bold cyberpunk aesthetic, glowing eyes, and advanced tech gear. Suitable for sci-fi narratives, stylized storytelling, and visual AI applications.',
                        'validation' => 'nullable|string',
                    ],
                ],
                'path_parameters' => [],
                'example' => [
                    'name' => 'cyber_hero_neo',
                    'quality' => 'high',
                    'gender' => 'male',
                    'images' => [
                        'https://publiish.io/ipfs/QmRBe3ZDEBDH18JEgDuFdTShzw3Xy1s94bY6dtcBAnH4tu',
                        'https://publiish.io/ipfs/QmRPNoFMcYFmzJuZgd4t3BDyfELAGCwNtGSb5i5AbXkcpf',
                        'https://publiish.io/ipfs/QmePMNQ1BYCsaJwCpA4sbGpYxgiEznzJwPDMHir9FdUiYN',
                        'https://publiish.io/ipfs/QmPnAKihJS1shKqnA4UqQ6bvkw29j8yFW4MJTb6KZA1e6Q',
                        'https://publiish.io/ipfs/QmdHRXQ8sX2d648gnCa2CXUjeJmreS8654vqwd9JS6m8GN',
                        'https://publiish.io/ipfs/QmPE5opZZhpeHypZzG3qJE5cbCNZ28SibBa9xo4MqsgF9H',
                        'https://publiish.io/ipfs/QmRTn93jATdpcpCg1nRfAExc8shh9Hmhbd8PHnXBrLJYAa',
                        'https://publiish.io/ipfs/QmTjCdTXQ2M1JPQHMuciYGQ2BWLVXum73PEJ8KY1znV4TV',
                    ],
                    'description' => 'A futuristic male character with a bold cyberpunk aesthetic, glowing eyes, and advanced tech gear. Suitable for sci-fi narratives, stylized storytelling, and visual AI applications.',
                ],
                'request_class_name' => LoraCharacterTrainRequest::class,
                'function_name' => 'trainLoraCharacter',
            ],
            [
                'name' => 'Classic Fast Image Generation',
                'description' => 'Convert descriptive text into images using Freepik Classic Fast AI engine.',
                'parameter' => [
                    'prompt' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Text to generate image from',
                        'example' => 'Crazy dog in the space',
                        'validation' => 'required|string|min:3',
                    ],
                    'negative_prompt' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Attributes to avoid in the generated image',
                        'example' => 'b&w, earth, cartoon, ugly',
                        'validation' => 'nullable|string|min:3',
                    ],
                    'guidance_scale' => [
                        'type' => 'number',
                        'required' => false,
                        'description' => 'Fidelity to the prompt',
                        'example' => 2,
                        'validation' => 'nullable|numeric|min:0|max:2',
                    ],
                    'seed' => [
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'Seed value for image reproducibility',
                        'example' => 42,
                        'validation' => 'nullable|integer|min:0|max:1000000',
                    ],
                    'num_images' => [
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'Number of images to generate',
                        'example' => 1,
                        'validation' => 'nullable|integer|min:1|max:4',
                    ],
                    'filter_nsfw' => [
                        'type' => 'boolean',
                        'required' => false,
                        'description' => 'Filter NSFW content',
                        'example' => true,
                        'validation' => 'nullable|boolean',
                    ],
                    'image' => [
                        'type' => 'object',
                        'required' => false,
                        'description' => 'Image properties.',
                        'example' => null,
                        'validation' => 'nullable|array',
                    ],
                    'styling' => [
                        'type' => 'object',
                        'required' => false,
                        'description' => 'Styling options.',
                        'example' => null,
                        'validation' => 'nullable|array',
                    ],
                ],
                'path_parameters' => [],
                'request_class_name' => ClassicFastGenerateRequest::class,
                'function_name' => 'generateClassicFastImage',
            ],
            [
                'name' => 'Google Imagen 3 Image Generation',
                'description' => 'Convert descriptive text into images using Google Imagen 3 AI engine.',
                'parameter' => [
                    'prompt' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'The prompt to generate an image from.',
                        'example' => 'Crazy dog in the space',
                        'validation' => 'required|string',
                    ],
                    'num_images' => [
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'The number of images to generate.',
                        'example' => 1,
                        'validation' => 'nullable|integer|min:1|max:4',
                    ],
                    'aspect_ratio' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['square_1_1', 'social_story_9_16', 'widescreen_16_9', 'traditional_3_4', 'classic_4_3'],
                        'description' => 'The aspect ratio of the generated image(s).',
                        'example' => 'square_1_1',
                        'validation' => 'nullable|string|in:square_1_1,social_story_9_16,widescreen_16_9,traditional_3_4,classic_4_3',
                    ],
                    'styling' => [
                        'type' => 'object',
                        'required' => false,
                        'description' => 'The styling options for the generated image(s).',
                        'example' => null,
                        'validation' => 'nullable|array',
                    ],
                    'person_generation' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['dont_allow', 'allow_adult', 'allow_all'],
                        'description' => 'Controls whether people can be generated.',
                        'example' => 'allow_adult',
                        'validation' => 'nullable|string|in:dont_allow,allow_adult,allow_all',
                    ],
                    'safety_settings' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['block_low_and_above', 'block_medium_and_above', 'block_only_high', 'block_none'],
                        'description' => 'The safety settings for the generation process.',
                        'example' => 'block_low_and_above',
                        'validation' => 'nullable|string|in:block_low_and_above,block_medium_and_above,block_only_high,block_none',
                    ],
                ],
                'path_parameters' => [],
                'example' => [],
                'request_class_name' => Imagen3GenerateRequest::class,
                'function_name' => 'generateImagen3',
            ],
            [
                'name' => 'Google Imagen 3 Image Generation Task Status',
                'description' => 'Get the status of the Imagen3 task',
                'parameter' => [],
                'path_parameters' => [
                    'task_id' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'ID of the Imagen3 generation task',
                        'example' => '046b6c7f-0b8a-43b9-b35d-6489e6daee91',
                        'validation' => 'required|string',
                    ],
                ],
                'request_class_name' => null,
                'function_name' => 'getImagen3TaskStatus',
            ],
            [
                'name' => 'Flux Dev Image Generation',
                'description' => 'Convert descriptive text input into images using Freepik Flux Dev AI engine.',
                'parameter' => [
                    'prompt' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'The text prompt for generation.',
                        'example' => 'A futuristic city floating in the sky',
                        'validation' => 'nullable|string',
                    ],
                    'aspect_ratio' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['square_1_1', 'classic_4_3', 'traditional_3_4', 'widescreen_16_9', 'social_story_9_16', 'standard_3_2', 'portrait_2_3', 'horizontal_2_1', 'vertical_1_2', 'social_post_4_5'],
                        'description' => 'The aspect ratio of the output image.',
                        'example' => 'square_1_1',
                        'validation' => 'nullable|string|in:square_1_1,classic_4_3,traditional_3_4,widescreen_16_9,social_story_9_16,standard_3_2,portrait_2_3,horizontal_2_1,vertical_1_2,social_post_4_5',
                    ],
                    'styling' => [
                        'type' => 'object',
                        'required' => false,
                        'description' => 'Styling options for the image.',
                        'example' => null,
                        'validation' => 'nullable|array',
                    ],
                    'seed' => [
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'The seed for the random number generator.',
                        'example' => 2147483648,
                        'validation' => 'nullable|integer|min:1|max:4294967295',
                    ],
                ],
                'path_parameters' => [],
                'example' => [
                    'prompt' => 'A futuristic city floating in the sky',
                    'aspect_ratio' => 'square_1_1',
                    'styling' => [
                        'effects' => [
                            'color' => 'softhue',
                            'framing' => 'portrait',
                            'lightning' => 'iridescent',
                        ],
                        'colors' => [
                            [
                                'color' => '#FF0000',
                                'weight' => 0.5,
                            ],
                        ],
                    ],
                    'seed' => 2147483648,
                ],
                'request_class_name' => FluxDevGenerateRequest::class,
                'function_name' => 'generateFluxDevImage',
            ],
            [
                'name' => 'Freepik Flux Dev Task Status',
                'description' => 'Get the status of the Flux Dev image generation task',
                'parameter' => [],
                'path_parameters' => [
                    'task_id' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'ID of the Flux Dev generation task',
                        'example' => '046b6c7f-0b8a-43b9-b35d-6489e6daee91',
                        'validation' => 'required|string',
                    ],
                ],
                'request_class_name' => null,
                'function_name' => 'getFluxDevTaskStatus',
            ],
            [
                'name' => 'Reimagine Flux Image Generation',
                'description' => 'Reimagine an input image using a text prompt and Freepik’s Flux AI engine.',
                'parameter' => [
                    'image' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Base64-encoded input image',
                        'example' => 'https://publiish.io/ipfs/QmPE5opZZhpeHypZzG3qJE5cbCNZ28SibBa9xo4MqsgF9H',
                        'validation' => 'required|string',
                    ],
                    'prompt' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Optional prompt for imagination',
                        'example' => 'A beautiful sunset over a calm ocean',
                        'validation' => 'nullable|string',
                    ],
                    'imagination' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['wild', 'subtle', 'vivid'],
                        'description' => 'Imagination type',
                        'example' => 'wild',
                        'validation' => 'nullable|string|in:wild,subtle,vivid',
                    ],
                    'aspect_ratio' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['original', 'square_1_1', 'classic_4_3', 'traditional_3_4', 'widescreen_16_9', 'social_story_9_16', 'standard_3_2', 'portrait_2_3', 'horizontal_2_1', 'vertical_1_2', 'social_post_4_5'],
                        'description' => 'Aspect ratio of the generated image',
                        'example' => 'square_1_1',
                        'validation' => 'nullable|string|in:original,square_1_1,classic_4_3,traditional_3_4,widescreen_16_9,social_story_9_16,standard_3_2,portrait_2_3,horizontal_2_1,vertical_1_2,social_post_4_5',
                    ],
                ],
                'path_parameters' => [],
                'example' => [
                    'image' => 'https://publiish.io/ipfs/QmPE5opZZhpeHypZzG3qJE5cbCNZ28SibBa9xo4MqsgF9H',
                    'prompt' => 'A beautiful sunset over a calm ocean',
                    'imagination' => 'wild',
                    'aspect_ratio' => 'square_1_1',
                ],
                'request_class_name' => ReimagineFluxRequest::class,
                'function_name' => 'reimagineFlux',
            ],
            [
                'name' => 'Upscale Image Editing',
                'description' => 'Upscale an image using Freepik\'s Magnific AI. Accepts a base64 image, aspect ratio, scale factor, optimization and styling preferences.',
                'parameter' => [
                    'image' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'URL of the image to upscale',
                        'example' => 'https://publiish.io/ipfs/QmPE5opZZhpeHypZzG3qJE5cbCNZ28SibBa9xo4MqsgF9H',
                        'validation' => 'required|string',
                    ],
                    'scale_factor' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['2x', '4x', '8x', '16x'],
                        'description' => 'The scaling factor to apply to the image.',
                        'example' => '2x',
                        'validation' => 'nullable|string|in:2x,4x,8x,16x',
                    ],
                    'optimized_for' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['standard', 'soft_portraits', 'hard_portraits', 'art_n_illustration', 'videogame_assets', 'nature_n_landscapes', 'films_n_photography', '3d_renders', 'science_fiction_n_horror'],
                        'description' => 'The optimization preset to use.',
                        'example' => 'standard',
                        'validation' => 'nullable|string|in:standard,soft_portraits,hard_portraits,art_n_illustration,videogame_assets,nature_n_landscapes,films_n_photography,3d_renders,science_fiction_n_horror',
                    ],
                    'prompt' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'A descriptive prompt to guide the upscaling.',
                        'example' => 'A vivid and high-detail fantasy landscape with towering crystal mountains, glowing waterfalls, and enchanted forests under a twilight sky',
                        'validation' => 'nullable|string',
                    ],
                    'creativity' => [
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'The level of creative freedom for the AI.',
                        'example' => 5,
                        'validation' => 'nullable|integer|min:-10|max:10',
                    ],
                    'hdr' => [
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'The level of High Dynamic Range to apply.',
                        'example' => 3,
                        'validation' => 'nullable|integer|min:-10|max:10',
                    ],
                    'resemblance' => [
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'How much the output should resemble the input.',
                        'example' => 0,
                        'validation' => 'nullable|integer|min:-10|max:10',
                    ],
                    'fractality' => [
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'The amount of fractal detail to add.',
                        'example' => -2,
                        'validation' => 'nullable|integer|min:-10|max:10',
                    ],
                    'engine' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['automatic', 'magnific_illusio', 'magnific_sharpy', 'magnific_sparkle'],
                        'description' => 'The AI engine to use for the upscaling process.',
                        'example' => 'automatic',
                        'validation' => 'nullable|string|in:automatic,magnific_illusio,magnific_sharpy,magnific_sparkle',
                    ],
                ],
                'path_parameters' => [],
                'example' => [
                    'image' => 'https://publiish.io/ipfs/QmPE5opZZhpeHypZzG3qJE5cbCNZ28SibBa9xo4MqsgF9H',
                    'scale_factor' => '2x',
                    'optimized_for' => 'standard',
                    'prompt' => 'A vivid and high-detail fantasy landscape with towering crystal mountains, glowing waterfalls, and enchanted forests under a twilight sky',
                    'creativity' => 5,
                    'hdr' => 3,
                    'resemblance' => 0,
                    'fractality' => -2,
                    'engine' => 'automatic',
                ],
                'request_class_name' => UpscaleImageRequest::class,
                'function_name' => 'upscale',
            ],
            [
                'name' => 'Upscale Image Editing Task Status',
                'description' => 'Get the status of the Magnific image upscaling task',
                'parameter' => [],
                'path_parameters' => [
                    'task_id' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'ID of the upscaling task',
                        'example' => '046b6c7f-0b8a-43b9-b35d-6489e6daee91',
                        'validation' => 'required|string',
                    ],
                ],
                'request_class_name' => null,
                'function_name' => 'getUpscalerTaskStatus',
            ],
            [
                'name' => 'Relight Image Editing',
                'description' => 'Relight an image using AI with custom styling, light source, and enhancement parameters.',
                'parameter' => [
                    'image' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Base64 image to relight',
                        'example' => 'https://publiish.io/ipfs/QmPE5opZZhpeHypZzG3qJE5cbCNZ28SibBa9xo4MqsgF9H',
                        'validation' => 'required|string',
                    ],
                    'prompt' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Prompt to guide the relighting process.',
                        'example' => 'A sunlit forest clearing at golden hour with rays piercing through the trees',
                        'validation' => 'nullable|string',
                    ],
                    'transfer_light_from_reference_image' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Reference image URL to transfer light from.',
                        'example' => 'https://publiish.io/ipfs/QmTjCdTXQ2M1JPQHMuciYGQ2BWLVXum73PEJ8KY1znV4TV',
                        'validation' => 'nullable|string',
                    ],
                    'transfer_light_from_lightmap' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Lightmap URL to transfer light from.',
                        'example' => 'https://publiish.io/ipfs/QmPnAKihJS1shKqnA4UqQ6bvkw29j8yFW4MJTb6KZA1e6Q',
                        'validation' => 'nullable|string',
                    ],
                    'light_transfer_strength' => [
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'The strength of the light transfer.',
                        'example' => 100,
                        'validation' => 'nullable|integer|min:0|max:100',
                    ],
                    'interpolate_from_original' => [
                        'type' => 'boolean',
                        'required' => false,
                        'description' => 'Whether to interpolate from the original image.',
                        'example' => false,
                        'validation' => 'nullable|boolean',
                    ],
                    'change_background' => [
                        'type' => 'boolean',
                        'required' => false,
                        'description' => 'Whether to change the background.',
                        'example' => true,
                        'validation' => 'nullable|boolean',
                    ],
                    'style' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['standard', 'darker_but_realistic', 'clean', 'smooth', 'brighter', 'contrasted_n_hdr', 'just_composition'],
                        'description' => 'The style to apply.',
                        'example' => 'standard',
                        'validation' => 'nullable|string|in:standard,darker_but_realistic,clean,smooth,brighter,contrasted_n_hdr,just_composition',
                    ],
                    'preserve_details' => [
                        'type' => 'boolean',
                        'required' => false,
                        'description' => 'Whether to preserve details.',
                        'example' => true,
                        'validation' => 'nullable|boolean',
                    ],
                    'advanced_settings' => [
                        'type' => 'object',
                        'required' => false,
                        'description' => 'Advanced relighting settings.',
                        'example' => null,
                        'validation' => 'nullable|array',
                    ],
                ],
                'path_parameters' => [],
                'example' => [
                    'image' => 'https://publiish.io/ipfs/QmPE5opZZhpeHypZzG3qJE5cbCNZ28SibBa9xo4MqsgF9H',
                    'prompt' => 'A sunlit forest clearing at golden hour with rays piercing through the trees',
                    'transfer_light_from_reference_image' => 'https://publiish.io/ipfs/QmTjCdTXQ2M1JPQHMuciYGQ2BWLVXum73PEJ8KY1znV4TV',
                    'transfer_light_from_lightmap' => 'https://publiish.io/ipfs/QmPnAKihJS1shKqnA4UqQ6bvkw29j8yFW4MJTb6KZA1e6Q',
                    'light_transfer_strength' => 100,
                    'interpolate_from_original' => false,
                    'change_background' => true,
                    'style' => 'standard',
                    'preserve_details' => true,
                    'advanced_settings' => [
                        'whites' => 50,
                        'blacks' => 50,
                        'brightness' => 50,
                        'contrast' => 50,
                        'saturation' => 50,
                        'engine' => 'automatic',
                        'transfer_light_a' => 'automatic',
                        'transfer_light_b' => 'automatic',
                        'fixed_generation' => false,
                    ],
                ],
                'request_class_name' => RelightImageRequest::class,
                'function_name' => 'relight',
            ],
            [
                'name' => 'Relight Image Editing Task Status',
                'description' => 'Get the status of the Relight task',
                'parameter' => [],
                'path_parameters' => [
                    'task_id' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'ID of the Relight task',
                        'example' => '046b6c7f-0b8a-43b9-b35d-6489e6daee91',
                        'validation' => 'required|string',
                    ],
                ],
                'request_class_name' => null,
                'function_name' => 'getRelightTaskStatus',
            ],
            [
                'name' => 'Style Transfer Image Editing',
                'description' => 'Style transfer an image using AI',
                'parameter' => [
                    'image' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Base64 Image to style transfer',
                        'example' => 'https://publiish.io/ipfs/QmPE5opZZhpeHypZzG3qJE5cbCNZ28SibBa9xo4MqsgF9H',
                        'validation' => 'required|string',
                    ],
                    'reference_image' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Base64 Reference image for style transfer',
                        'example' => 'https://publiish.io/ipfs/QmTjCdTXQ2M1JPQHMuciYGQ2BWLVXum73PEJ8KY1znV4TV',
                        'validation' => 'required|string',
                    ],
                    'prompt' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'A text prompt to guide the style transfer.',
                        'example' => 'A peaceful mountain cabin at sunrise, surrounded by pine trees and light morning mist',
                        'validation' => 'nullable|string',
                    ],
                    'style_strength' => [
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'The strength of the style to apply.',
                        'example' => 100,
                        'validation' => 'nullable|integer|min:0|max:100',
                    ],
                    'structure_strength' => [
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'The strength of the original structure to preserve.',
                        'example' => 50,
                        'validation' => 'nullable|integer|min:0|max:100',
                    ],
                    'is_portrait' => [
                        'type' => 'boolean',
                        'required' => false,
                        'description' => 'Indicates if the image is a portrait.',
                        'example' => false,
                        'validation' => 'nullable|boolean',
                    ],
                    'portrait_style' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['standard', 'pop', 'super_pop'],
                        'description' => 'Portrait style',
                        'example' => 'standard',
                        'validation' => 'nullable|string|in:standard,pop,super_pop',
                    ],
                    'portrait_beautifier' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['beautify_face', 'beautify_face_max'],
                        'description' => 'Portrait beautifier',
                        'example' => 'beautify_face',
                        'validation' => 'nullable|string|in:beautify_face,beautify_face_max',
                    ],
                    'flavor' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['faithful', 'gen_z', 'psychedelia', 'detaily', 'clear', 'donotstyle', 'donotstyle_sharp'],
                        'description' => 'Flavor of the transferring style',
                        'example' => 'faithful',
                        'validation' => 'nullable|string|in:faithful,gen_z,psychedelia,detaily,clear,donotstyle,donotstyle_sharp',
                    ],
                    'engine' => [
                        'type' => 'string',
                        'required' => false,
                        'enum' => ['balanced', 'definio', 'illusio', '3d_cartoon', 'colorful_anime', 'caricature', 'real', 'super_real', 'softy'],
                        'description' => 'Engine for style transfer',
                        'example' => 'balanced',
                        'validation' => 'nullable|string|in:balanced,definio,illusio,3d_cartoon,colorful_anime,caricature,real,super_real,softy',
                    ],
                    'fixed_generation' => [
                        'type' => 'boolean',
                        'required' => false,
                        'description' => 'Fixed generation flag',
                        'example' => false,
                        'validation' => 'nullable|boolean',
                    ],
                ],
                'path_parameters' => [],
                'example' => [
                    'image' => 'https://publiish.io/ipfs/QmPE5opZZhpeHypZzG3qJE5cbCNZ28SibBa9xo4MqsgF9H',
                    'reference_image' => 'https://publiish.io/ipfs/QmTjCdTXQ2M1JPQHMuciYGQ2BWLVXum73PEJ8KY1znV4TV',
                    'prompt' => 'A peaceful mountain cabin at sunrise, surrounded by pine trees and light morning mist',
                    'style_strength' => 100,
                    'structure_strength' => 50,
                    'is_portrait' => false,
                    'portrait_style' => 'standard',
                    'portrait_beautifier' => 'beautify_face',
                    'flavor' => 'faithful',
                    'engine' => 'balanced',
                    'fixed_generation' => false,
                ],
                'request_class_name' => StyleTransferRequest::class,
                'function_name' => 'styleTransfer',
            ],
            [
                'name' => 'Style Transfer Image Editing Task Status',
                'description' => 'Get the status of the Style Transfer task',
                'parameter' => [],
                'path_parameters' => [
                    'task_id' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'ID of the Style Transfer task',
                        'example' => '046b6c7f-0b8a-43b9-b35d-6489e6daee91',
                        'validation' => 'required|string',
                    ],
                ],
                'request_class_name' => null,
                'function_name' => 'getStyleTransferTaskStatus',
            ],
            [
                'name' => 'Remove Background Image Editing',
                'description' => 'Remove the background of an image via URL',
                'parameter' => [
                    'image_url' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'The URL of the image whose background needs to be removed',
                        'example' => 'https://publiish.io/ipfs/QmPE5opZZhpeHypZzG3qJE5cbCNZ28SibBa9xo4MqsgF9H',
                        'validation' => 'required|string|url',
                    ],
                ],
                'path_parameters' => [],
                'example' => [
                    'image_url' => 'https://publiish.io/ipfs/QmPE5opZZhpeHypZzG3qJE5cbCNZ28SibBa9xo4MqsgF9H',
                ],
                'request_class_name' => RemoveBackgroundRequest::class,
                'function_name' => 'removeBackgroundFromImage',
            ],
            [
                'name' => 'Expand Image Editing',
                'description' => 'Expand an image using AI Flux Pro',
                'parameter' => [
                    'image' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Base64 image to expand',
                        'example' => 'https://publiish.io/ipfs/QmPE5opZZhpeHypZzG3qJE5cbCNZ28SibBa9xo4MqsgF9H',
                        'validation' => 'required|string',
                    ],
                    'prompt' => [
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Description to guide expansion',
                        'example' => 'A panoramic view of a serene beach with gentle waves, golden sand, and a vibrant sunset sky extending beyond the frame',
                        'validation' => 'nullable|string',
                    ],
                    'left' => [
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'Pixels to expand on the left',
                        'example' => 2048,
                        'validation' => 'nullable|integer|min:0|max:2048',
                    ],
                    'right' => [
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'Pixels to expand on the right',
                        'example' => 2048,
                        'validation' => 'nullable|integer|min:0|max:2048',
                    ],
                    'top' => [
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'Pixels to expand on the top',
                        'example' => 2048,
                        'validation' => 'nullable|integer|min:0|max:2048',
                    ],
                    'bottom' => [
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'Pixels to expand on the bottom',
                        'example' => 2048,
                        'validation' => 'nullable|integer|min:0|max:2048',
                    ],
                ],
                'path_parameters' => [],
                'example' => [
                    'image' => 'https://publiish.io/ipfs/QmPE5opZZhpeHypZzG3qJE5cbCNZ28SibBa9xo4MqsgF9H',
                    'prompt' => 'A panoramic view of a serene beach with gentle waves, golden sand, and a vibrant sunset sky extending beyond the frame',
                    'left' => 2048,
                    'right' => 2048,
                    'top' => 2048,
                    'bottom' => 2048,
                ],
                'request_class_name' => ImageExpandFluxProRequest::class,
                'function_name' => 'imageExpandFluxPro',
            ],
            [
                'name' => 'Expand Image Editing Task Status',
                'description' => 'Get the status of one image expand task',
                'parameter' => [],
                'path_parameters' => [
                    'task_id' => [
                        'type' => 'string',
                        'required' => true,
                        'description' => 'ID of the image expand task',
                        'example' => '046b6c7f-0b8a-43b9-b35d-6489e6daee91',
                        'validation' => 'required|string',
                    ],
                ],
                'request_class_name' => null,
                'function_name' => 'getImageExpandFluxProTaskStatus',
            ],
        ];
    }
}
