<?php

namespace App\Http\Requests\User;

use App\Http\Requests\BaseFormRequest;

class CreateUserRequest extends BaseFormRequest
{
    public function rules(): array
    {
        return [
            'name' => 'required|string|min:1|max:255',
            'restaurant_name' => 'required|string|min:1|max:255',
            'email' => 'required|string|email|min:1|max:255',
            'email_verified_at' => 'nullable|date',
            'is_approved' => 'required|integer|min:0|max:1',
            'password' => 'required|string|min:1|max:255',
            'two_factor_secret' => 'nullable|string',
            'two_factor_recovery_codes' => 'nullable|string',
            'two_factor_confirmed_at' => 'nullable|date',
            'country_code' => 'required|string|min:1|max:100',
            'mobile' => 'required|string|min:1|max:255',
            'whatsapp' => 'nullable|string|min:1|max:255',
            'telegram_group_id' => 'nullable|string|min:1|max:255',
            'send_daily_report' => 'nullable|integer|min:0|max:1',
            'send_weekly_report' => 'nullable|integer|min:0|max:1',
            'send_monthly_report' => 'nullable|integer|min:0|max:1',
            'user_type' => 'required|integer',
            'parent_id' => 'required|integer',
            'approved' => 'required|integer|min:0|max:1',
            'referral_code' => 'nullable|string|min:1|max:255',
            'company_name' => 'required|string|min:1|max:255',
            'company_title' => 'nullable|string|min:1|max:255',
            'orderific_client' => 'nullable|string|min:1|max:255',
            'refer_leads' => 'nullable|string|min:1|max:255',
            'business_tenure' => 'nullable|string|min:1|max:255',
            'remember_token' => 'nullable|string|min:1|max:100',
            'profile' => 'nullable|string|min:1|max:255',
            'product_service' => 'nullable|string|min:1|max:255',
            'zoom_info' => 'nullable|string|min:1|max:255',
            'company_website' => 'nullable|string|min:1|max:255',
            'industry' => 'nullable|string|min:1|max:255',
            'location' => 'nullable|string|min:1|max:255',
            'about' => 'nullable|string|min:1|max:255',
            'expertskill' => 'nullable|string|min:1|max:255',
            'expert_level' => 'nullable|string|min:1|max:255',
            'copy' => 'nullable|string|min:1|max:255',
            'graphics' => 'nullable|string|min:1|max:255',
            'video' => 'nullable|string|min:1|max:255',
            'audio' => 'nullable|string|min:1|max:255',
            'email_otp' => 'nullable|string|min:1|max:20',
            'email_otp_expired_at' => 'nullable|date',
            'forgot_otp' => 'nullable|string|min:1|max:20',
            'forgot_otp_expired_at' => 'nullable|date',
            'otp_attempt' => 'nullable|integer|min:0|max:10',
            'forgot_otp_attempt' => 'nullable|integer|min:0|max:10',
            'creator_api_key' => 'nullable|string|min:1|max:255',
            'creator_secure_key' => 'nullable|string|min:1|max:255',
            'brand_key' => 'nullable|string|min:1|max:255',
            'referred_by' => 'nullable|integer',
            'currency_code' => 'nullable|string|min:1|max:255',
            'sub_domain_brand_id' => 'nullable|integer',
            'profile_cid' => 'nullable|string|min:1|max:255',
            'profile_image_name' => 'nullable|string|min:1|max:255',
            'user_code' => 'nullable|string|min:1|max:255',
            'is_testing' => 'nullable|integer|min:0|max:1',
            'user_auth_token' => 'nullable|string|min:1|max:255',
            'driver_currency_id' => 'nullable|integer',
            'first_name' => 'nullable|string|min:1|max:191',
            'middle_name' => 'nullable|string|min:1|max:191',
            'last_name' => 'nullable|string|min:1|max:191',
            'login_pin' => 'nullable|integer',
            'bio' => 'nullable|date',
            'last_login_at' => 'nullable|date',
            'status' => 'required|integer|in:1,2',
            'share_mode' => 'nullable|integer|in:0,1',
            'delete_reason' => 'nullable|string|min:1|max:191',
            'default_address' => 'nullable|string|min:1|max:191',
        ];
    }
}
